version: "3.8"

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    ports:
      - "80:8096"
    volumes:
      - "jellyfin_config:/config"
      - "./media:/media"

  jellyfin-alexa-skill:
    image: ghcr.io/infinityofspace/jellyfin_alexa_skill:latest
    restart: unless-stopped
    depends_on:
      - jellyfin
      - skill_db
    ports:
      - "1456:1456"
    volumes:
      - "./skill.conf:/skill/config/skill.conf"
    healthcheck:
      test: ["CMD", "wget", "--spider", "--tries=1", "http://localhost:1456/healthy"]

  db:
    image: postgres:14.4-alpine3.16
    restart: unless-stopped
    volumes:
      - "skill_db_data:/var/lib/postgresql/data"

volumes:
  jellyfin_config:
  skill_db_data:
